#!/usr/bin/env python3
"""
YOLO Annotation Visualization Script
Visualizes 14-point skeletons generated by YOLO models.
"""

import json
import cv2
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from typing import List, Dict, Tuple
import random
import argparse

def get_project_root() -> Path:
    current_path = Path(__file__).resolve().parent
    for parent in [current_path] + list(current_path.parents):
        if (parent / "data").exists() or (parent / ".git").exists() or (parent / "requirements.txt").exists():
            return parent
    return Path.cwd()

PROJECT_ROOT = get_project_root()

# Skeleton Definition
SKELETON_CONNECTIONS = [
    (0, 1), (1, 2), (1, 3), (2, 4), (4, 6), (3, 5), (5, 7),
    (2, 8), (3, 9), (8, 9), (8, 10), (10, 12), (9, 11), (11, 13)
]

COLORS = {
    'skeleton': (0, 255, 255), 'keypoints': (0, 255, 0),
    'bbox': (255, 0, 0), 'text': (255, 255, 255),
}

def find_annotated_directories(data_root: Path) -> List[Path]:
    annotated_dirs = []
    # Search specifically for YOLO annotations now
    for yolo_file in data_root.rglob("yolo_annotations.json"):
        parent_dir = yolo_file.parent
        frames_dir = parent_dir / "frames"
        if frames_dir.exists() and list(frames_dir.glob("*.jpg")):
            annotated_dirs.append(parent_dir)
    return sorted(annotated_dirs)

def get_random_annotated_frames(annotated_dir: Path, num_samples: int = 1):
    frames_dir = annotated_dir / "frames"
    yolo_path = annotated_dir / "yolo_annotations.json"
    
    with open(yolo_path, 'r') as f:
        yolo_data = json.load(f)
        
    frame_annotations = {}
    for ann in yolo_data['annotations']:
        frame_num = ann['frame_number']
        if frame_num not in frame_annotations:
            frame_annotations[frame_num] = []
        frame_annotations[frame_num].append(ann)
        
    available_frames = list(frame_annotations.keys())
    if not available_frames: return []
    
    sampled_frame_nums = random.sample(available_frames, min(num_samples, len(available_frames)))
    
    result = []
    for frame_num in sampled_frame_nums:
        frame_path = frames_dir / f"frame_{frame_num:06d}.jpg"
        if frame_path.exists():
            result.append((frame_path, frame_annotations[frame_num]))
    return result

def draw_skeleton_on_image(img, annotation):
    img = img.copy()
    keypoints = annotation['keypoints']
    
    kpts = [(keypoints[i], keypoints[i+1], keypoints[i+2]) for i in range(0, len(keypoints), 3)]
    
    # Draw skeleton
    for p1_idx, p2_idx in SKELETON_CONNECTIONS:
        x1, y1, v1 = kpts[p1_idx]
        x2, y2, v2 = kpts[p2_idx]
        if v1 > 0 and v2 > 0:
            cv2.line(img, (int(x1), int(y1)), (int(x2), int(y2)), COLORS['skeleton'], 2)
            
    # Draw keypoints
    for x, y, v in kpts:
        if v > 0:
            cv2.circle(img, (int(x), int(y)), 4, COLORS['keypoints'], -1)
            cv2.circle(img, (int(x), int(y)), 4, (0, 0, 0), 1)
            
    # Draw bbox
    if 'bbox' in annotation:
        x, y, w, h = map(int, annotation['bbox'])
        cv2.rectangle(img, (x, y), (x + w, y + h), COLORS['bbox'], 2)
        label = f"Person {annotation.get('person_id', 0)}"
        cv2.putText(img, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, COLORS['text'], 1)
        
    return img

def visualize_samples(data_root: List, num_samples: int = 4):
    # annotated_dirs = find_annotated_directories(data_root)
    annotated_dirs = data_root
    if not annotated_dirs:
        print(f"❌ No YOLO annotated directories found!")
        return

    all_samples = []
    num_dirs = min(len(annotated_dirs), max(1, num_samples))
    sampled_dirs = random.sample(annotated_dirs, num_dirs)
    
    for directory in sampled_dirs:
        all_samples.extend([(directory, path, anns) for path, anns in get_random_annotated_frames(directory, 2)])
        
    if len(all_samples) > num_samples:
        all_samples = random.sample(all_samples, num_samples)

    cols = min(3, len(all_samples))
    rows = (len(all_samples) + cols - 1) // cols
    fig = plt.figure(figsize=(6 * cols, 6 * rows))
    fig.suptitle('YOLO Annotations Visualization', fontsize=16, fontweight='bold')
    
    for idx, (directory, frame_path, annotations) in enumerate(all_samples, 1):
        img = cv2.imread(str(frame_path))
        for ann in annotations:
            img = draw_skeleton_on_image(img, ann)
            
        ax = plt.subplot(rows, cols, idx)
        ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        ax.axis('off')
        
        is_olympic = "olympic" in str(directory).lower()
        model_str = "Custom" if is_olympic else "Generic"
        ax.set_title(f"{directory.name}\nModel: {model_str} | {len(annotations)} person(s)", fontsize=10)
        
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=str, default="data/DATASET")
    parser.add_argument("--num-samples", type=int, default=10)
    args = parser.parse_args()
    
    visualize_samples([PROJECT_ROOT / args.data_dir / "V4", PROJECT_ROOT / args.data_dir / "V6"], args.num_samples)